### ISSUE TITLE
Conflicts with Tensorflow nco and netcdf4 packages

### ISSUE THREAD

**Issue by manmeet3591** [jessaustin/monthdelta#1]
Hi

This package monthdelta is great but it conflicts with Tensorflow, nco and netcdf4 packages

**Comment by jessaustin** [comment]
I'm not surprised. I haven't supported this package for at least 8 years. Python distribution annoyances have pretty much chased me away from the language altogether. It might be better now, but I wouldn't know. Feel free to fork or whatever. Good luck!
